// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  type CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  type ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  type SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from '../index.js';
export type SubscriptionError = {
  totalHostExecutionDurationMicros: bigint;
  requestId: number | undefined;
  queryId: number | undefined;
  tableId: number | undefined;
  error: string;
};

/**
 * A namespace for generated helper functions.
 */
export namespace SubscriptionError {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement(
        'totalHostExecutionDurationMicros',
        AlgebraicType.createU64Type()
      ),
      new ProductTypeElement(
        'requestId',
        AlgebraicType.createOptionType(AlgebraicType.createU32Type())
      ),
      new ProductTypeElement(
        'queryId',
        AlgebraicType.createOptionType(AlgebraicType.createU32Type())
      ),
      new ProductTypeElement(
        'tableId',
        AlgebraicType.createOptionType(AlgebraicType.createU32Type())
      ),
      new ProductTypeElement('error', AlgebraicType.createStringType()),
    ]);
  }

  export function serialize(
    writer: BinaryWriter,
    value: SubscriptionError
  ): void {
    SubscriptionError.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): SubscriptionError {
    return SubscriptionError.getTypeScriptAlgebraicType().deserialize(reader);
  }
}
