// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  type CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  type ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  type SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from '../index.js';
import { DatabaseUpdate as __DatabaseUpdate } from './database_update_type.js';

export type TransactionUpdateLight = {
  requestId: number;
  update: __DatabaseUpdate;
};

/**
 * A namespace for generated helper functions.
 */
export namespace TransactionUpdateLight {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('requestId', AlgebraicType.createU32Type()),
      new ProductTypeElement(
        'update',
        __DatabaseUpdate.getTypeScriptAlgebraicType()
      ),
    ]);
  }

  export function serialize(
    writer: BinaryWriter,
    value: TransactionUpdateLight
  ): void {
    TransactionUpdateLight.getTypeScriptAlgebraicType().serialize(
      writer,
      value
    );
  }

  export function deserialize(reader: BinaryReader): TransactionUpdateLight {
    return TransactionUpdateLight.getTypeScriptAlgebraicType().deserialize(
      reader
    );
  }
}
